# Generated by Django 4.0.2 on 2022-03-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappocalypse', '0003_alter_bag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='climate',
            field=models.CharField(choices=[('Dry', 'Dry'), ('Tropical', 'Tropical'), ('Continental', 'Continental'), ('Temperate', 'Temperate'), ('Polar', 'Polar'), ('All Climate', 'All Climate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='environment',
            field=models.CharField(choices=[('Forest', 'Forest'), ('Rocky', 'Rocky'), ('Grassland', 'Grassland'), ('Desert', 'Desert'), ('Tundra', 'Tundra'), ('Marine', 'Marine'), ('All Environment', 'All Environment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='landform',
            field=models.CharField(choices=[('Mountains', 'Mountains'), ('Hills', 'Hills'), ('Plateau', 'Plateau'), ('Plain', 'Plain'), ('Ocean', 'Ocean'), ('All Landform', 'All Landform')], max_length=30),
        ),
    ]
