# Generated by Django 4.0.2 on 2022-03-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappocalypse', '0005_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Landform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='landform',
        ),
        migrations.AlterField(
            model_name='bag',
            name='climate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappocalypse.climate'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappocalypse.environment'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='landform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappocalypse.landform'),
        ),
        migrations.AddField(
            model_name='item',
            name='climate',
            field=models.ManyToManyField(blank=True, related_name='climates', to='myappocalypse.Climate'),
        ),
        migrations.AddField(
            model_name='item',
            name='environment',
            field=models.ManyToManyField(blank=True, related_name='environments', to='myappocalypse.Environment'),
        ),
        migrations.AddField(
            model_name='item',
            name='landform',
            field=models.ManyToManyField(blank=True, related_name='landforms', to='myappocalypse.Landform'),
        ),
    ]
