# Generated by Django 4.0.2 on 2022-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappocalypse', '0006_climate_environment_landform_remove_item_climate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='external',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
