# Generated by Django 4.0.2 on 2022-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappocalypse', '0014_recommendation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
