# Generated by Django 4.0.2 on 2022-03-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappocalypse', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
