# Generated by Django 4.0.2 on 2022-03-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappocalypse', '0017_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
